const portNames = {
    "1": "TCP Port Service Multiplexer",
    "2": "Management Utility",
    "3": "Compression Process",
    "5": "Remote Job Entry",
    "7": "Echo",
    "9": "Discard Protocol",
    "11": "Active Users",
    "13": "Daytime Protocol",
    "17": "Quote of the Day",
    "18": "Message Send Protocol",
    "19": "Character Generator",
    "20": "FTP - Data",
    "21": "FTP - Control",
    "22": "SSH Remote Login Protocol",
    "23": "Telnet",
    "25": "Simple Mail Transfer Protocol (SMTP)",
    "26": "RSFTP",
    "37": "Time",
    "39": "Resource Location Protocol",
    "42": "Host Name Server",
    "43": "WHOIS Protocol",
    "49": "Login Host Protocol (Login Server)",
    "53": "Domain Name System (DNS)",
    "69": "Trivial File Transfer Protocol (TFTP)",
    "70": "Gopher Services",
    "79": "Finger",
    "80": "HTTP",
    "81": "Torpark - Onion Routing",
    "82": "Torpark - Control",
    "88": "Kerberos",
    "101": "NIC Host Name Server",
    "102": "ISO-TSAP Class 0",
    "107": "Remote Telnet Service",
    "109": "Post Office Protocol v2 (POP2)",
    "110": "Post Office Protocol v3 (POP3)",
    "111": "ONC RPC (SunRPC)",
    "113": "Authentication Service",
    "115": "Simple File Transfer Protocol (SFTP)",
    "117": "UUCP Path Service",
    "118": "SQL Services",
    "119": "Network News Transfer Protocol (NNTP)",
    "123": "Network Time Protocol (NTP)",
    "137": "NetBIOS Name Service",
    "138": "NetBIOS Datagram Service",
    "139": "NetBIOS Session Service",
    "143": "Internet Message Access Protocol (IMAP)",
    "161": "Simple Network Management Protocol (SNMP)",
    "162": "Simple Network Management Protocol Trap (SNMPTRAP)",
    "177": "X Display Manager Control Protocol (XDMCP)",
    "178": "NextStep Window Server",
    "179": "Border Gateway Protocol (BGP)",
    "194": "Internet Relay Chat (IRC)",
    "199": "SMUX",
    "201": "AppleTalk Routing Maintenance",
    "202": "AppleTalk Name Binding",
    "204": "AppleTalk Echo",
    "206": "AppleTalk Zone Information",
    "209": "The Quick Mail Transfer Protocol",
    "210": "ANSI Z39.50",
    "213": "IPX",
    "220": "Internet Message Access Protocol v3 (IMAP3)",
    "245": "LINK",
    "347": "Display Support Protocol",
    "363": "RSVP Tunnel",
    "369": "Rpc2portmap",
    "370": "codaauth2",
    "372": "ListProcessor",
    "389": "Lightweight Directory Access Protocol (LDAP)",
    "434": "Mobile IP Agent",
    "435": "Mobil IP Migrate",
    "443": "HTTP Secure (HTTPS)",
    "444": "Simple Network Paging Protocol (SNPP)",
    "445": "Microsoft-DS",
    "464": "Kerberos - Change/Set password",
    "468": "Protocols",
    "487": "Display Manager",
    "488": "Unassigned",
    "500": "Internet Security Association and Key Management Protocol (ISAKMP)",
    "512": "Remote Process Execution",
    "513": "Remote Login (rlogin)",
    "514": "Remote Shell (rsh)",
    "515": "Line Printer Daemon (LPD)",
    "517": "Talk",
    "518": "NTalk",
    "520": "Routing Information Protocol (RIP)",
    "525": "Timeserver",
    "530": "Remote procedure call (RPC)",
    "531": "Chat",
    "532": "Netnews",
    "533": "For Emergency Broadcasts",
    "540": "UUCP (Unix-to-Unix Copy Protocol)",
    "543": "Kerberos (krb5) Login",
    "544": "Kerberos (krb5) Admin",
    "548": "AFP over TCP",
    "556": "Remotefs",
    "563": "NNTP over TLS/SSL (NNTPS)",
    "587": "E-mail message submission (SMTP)",
    "591": "FileMaker 6.0 (and later) Web Sharing (HTTP Alternate)",
    "631": "Internet Printing Protocol (IPP)",
    "636": "Lightweight Directory Access Protocol over TLS/SSL (LDAPS)",
    "655": "Tinc Control Port",
    "706": "Secure Internet Live Conferencing (SILC)",
    "749": "Kerberos (klogin)",
    "750": "Kerberos (kshell)",
    "765": "Webster",
    "767": "Phone",
    "873": "rsync",
    "992": "Telnet over TLS/SSL",
    "993": "IMAP4 over TLS/SSL (IMAPS)",
    "995": "POP3 over TLS/SSL (POP3S)",
    "1023": "Reserved",
    "1080": "SOCKS proxy"
}
    
export default portNames;



  